### ISSUE TITLE
A "package 'six' issue" happened when running 'docker build'(in master-cpp branch)

### ISSUE THREAD

**Issue by BarryAlanPan** [ed-asriyan/tgs-to-gif#15]
<img width="1513" alt="Xnip2020-06-02_15-02-08" src="https://user-images.githubusercontent.com/44538391/83490415-91913c00-a4e2-11ea-8b51-241ec2a32a49.png">
It seems like there's something happened in the docker environment, and I can't figure it out.(in master-cpp branch)

**Comment by BarryAlanPan** [comment]
I also tried to install it in my Mac(Catalina), and it showed the same error

**Comment by ed-asriyan** [comment]
@BarryAlanPan, I updated master-cpp branch, problem should be resolved. Please, try again.
