### ISSUE TITLE
it give error when i tried to use whole folder

### ISSUE THREAD

**Issue by SauravDharwadkar** [ed-asriyan/tgs-to-gif#17]
./tgs_to_gif ./webp 

terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_filebuf::xsgetn error reading the file: Is a directory
[1]    22537 abort (core dumped)  tgs_to_gif ./webp

**Comment by ed-asriyan** [comment]
C++ version of converter does not support directories. Please, run run the program separately:
```command
for F in ./webp; do ./tgs_to_gif $F; done 
```

**Comment by SauravDharwadkar** [comment]
see latest pull request

**Comment by ed-asriyan** [comment]
closed by #18
