### ISSUE TITLE
Request Code

### ISSUE THREAD

**Issue by Krishna-Singhal** [ed-asriyan/tgs-to-gif#19]
so you make telegram animated stickers to gif but is there any Bot who will convert gif to telegram animated stickers
or give me Code or library to do it

**Comment by ed-asriyan** [comment]
Please take a look at [giftolottie](https://github.com/bodqhrohro/giftolottie) project.

**Comment by Krishna-Singhal** [comment]
> Please take a look at [giftolottie](https://github.com/bodqhrohro/giftolottie) project.

but how can I use this 
also bot is not found

**Comment by SauravDharwadkar** [comment]
you have to program bot on own  , use telethon create simple bot download file to local run giftolottie on input and upload the generated tgs file

**Comment by sentinm** [comment]
> > Please take a look at [giftolottie](https://github.com/bodqhrohro/giftolottie) project.
> 
> but how can I use this 
> also bot is not found

I just make a bot but it don't use cache so converting to gif take time with gif encoding,
