### ISSUE TITLE
nested directory  support

### ISSUE THREAD

**Issue by thewayur** [ed-asriyan/tgs-to-gif#20]
can u please or guide me to convert nested folders?

a hint might be helpful too :)

**Comment by ed-asriyan** [comment]
Please checkout README. You can use docker (https://github.com/ed-asriyan/tgs-to-gif#using-docker) or npm (https://github.com/ed-asriyan/tgs-to-gif#convert) tools. Both of them support nested folders

**Comment by thewayur** [comment]
> Please checkout README. You can use docker (https://github.com/ed-asriyan/tgs-to-gif#using-docker) or npm (https://github.com/ed-asriyan/tgs-to-gif#convert) tools. Both of them support nested folders

thanks,
i have a personal query regarding tgs-to-gif, please reply me in fb or insta. msg u already:)

hope u wont mind my personal message :)
