### ISSUE TITLE
Docker build 

### ISSUE THREAD

**Issue by huehnerlady** [ed-asriyan/tgs-to-gif#23]
Hi,
I am using Windows 10 with cmd or WSL and docker for windows.
I tried to build the docker image with the command in the readme `docker build -t tgs-to-gif .`

I get the error logs:
```
Step 10/15 : RUN npm ci
 ---> Running in a68b9cca070e
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://git@github.com/ed-asriyan/puppeteer-lottie.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
I tried this with WSL and Ubuntu bash and with CMD from Windows10 directly and got the same output

Any Idea what I am doing wrong?

**Comment by ed-asriyan** [comment]
@huehnerlady hi! This issue should be resolved. Please try again.
