### ISSUE TITLE
Add feature to send a sticker set link and return a zip with all stickers in gif

### ISSUE THREAD

**Issue by huehnerlady** [ed-asriyan/tgs-to-gif#24]
Hi,

I would like to have a feature in the telegram bot to send a link with a sticker set and then receive a zip file with all stickers included in that set in GIF format.

Would that be possible to implement?

**Comment by ed-asriyan** [comment]
Hello!
Sticker pack generating will bring several problems:
1. Processing will took a long time to wait
2. Resulting zip size may reach telegram file size limit, that make impossible to convert some sticker packs

Another way is generate two or more archives. Unfortunately, not I do not enough time for development, but I'll try to implement it when I find the time.

**Comment by ed-asriyan** [comment]
Hello again! [@tgstogifbot](https://t.me/tgstogifbot) now supports batch mode. Just send him a link to sticker pack, and you will receive all converted stickers in it.
