### ISSUE TITLE
The --height HEIGHT  --width WIDTH  don't work 

### ISSUE THREAD

**Issue by joaopixeles** [ed-asriyan/tgs-to-gif#25]
Every time that I run the command the output is always the same size, and the animation is cut it.
![sticker tgs](https://user-images.githubusercontent.com/66826523/96201602-a109a280-0f22-11eb-97af-3e80299562a0.gif)

**Comment by ed-asriyan** [comment]
what version of gifski are you using?

**Comment by joaopixeles** [comment]
gifski 1.2.1

**Comment by ed-asriyan** [comment]
> gifski 1.2.1

Please, downgrade to 0.10.4
