### ISSUE TITLE
how can i set the gif size with the command param

### ISSUE THREAD

**Issue by diybl** [ed-asriyan/tgs-to-gif#3]
if i need create 256x256
how ？

**Comment by ed-asriyan** [comment]
You can pass parameters into function [here](https://github.com/ed-asriyan/tgs-to-gif/blob/ae24f6b1cc8623e291a55afd407d593a2f50ab4e/cli.js#L11):
```javascript
convertFile(filePath, {output: `${filePath}.gif`, browser, width: 256, height: 256});
```
and run the script as usual.

I will add these parameters to the script call arguments later.

**Comment by ed-asriyan** [comment]
Now you can pass gif size as command params:
```
node cli.js --width 256 /tmp/aniiv8i4yba.tgs
```
