### ISSUE TITLE
Bot Doesn't work, returns zip size of 22 B aka empty.

### ISSUE THREAD

**Issue by xoxaxo** [ed-asriyan/tgs-to-gif#31]
.

**Comment by xoxaxo** [comment]
It looks like you have to clear your cache, or delete those empty archives (zip's) so your bot will regenerate them again.

**Comment by ed-asriyan** [comment]
Please send a link to this sticker pack

**Comment by xoxaxo** [comment]
https://t.me/addstickers/otherdimensions

**Comment by ed-asriyan** [comment]
> https://t.me/addstickers/otherdimensions

Cache for this sticker pack has been reset. Please Try again
