### ISSUE TITLE
Empty Zip Folder

### ISSUE THREAD

**Issue by EmmaFiveCents** [ed-asriyan/tgs-to-gif#32]
I sent stickers from the Bubo the Scarfcat pack (and the whole pack) to it and it only sends back empty zip files. I tried with one from a different pack and it worked fine. 
![Screenshot_20210110-214754_Telegram](https://user-images.githubusercontent.com/77261168/104150076-88781f80-538d-11eb-837d-bc75044613d3.jpg)

**Comment by ed-asriyan** [comment]
fixed
