### ISSUE TITLE
Jam sticker conversion request returns empty zip files

### ISSUE THREAD

**Issue by phil-bryant** [ed-asriyan/tgs-to-gif#33]
Good morning, Ed.

I thought you might like to know that ♡♡♡ @tgstogifbot ♡♡♡ returns empty zip files upon requests to convert stickers from Jam, aka SweetJam. I've seen the same behavior from two different stickers, two different telegram clients, on two different OSes.

Sticker pack: [https://t.me/addstickers/SweetJam](https://t.me/addstickers/SweetJam)
Stickers tried: 👋 and 👍
Returned zip: [SweetJam-512px.zip](https://github.com/ed-asriyan/tgs-to-gif/files/5856398/SweetJam-512px.zip)
Screen shot from Macbook pro:
- <img width="300" alt="Screen_Shot_2021-01-22_at_8 14 47_AM_70" src="https://user-images.githubusercontent.com/77843345/105502268-e6104400-5c8a-11eb-9964-a865b0911486.png">
Telegram macOS Client v2.5.1:
- <img width="300" alt="Telegram Desktop Client Version" src="https://user-images.githubusercontent.com/77843345/105502786-6b93f400-5c8b-11eb-8ae5-064bd43381d3.png">
macOS Big Sur v11.0.1:
- <img width="300" alt="Big Sur" src="https://user-images.githubusercontent.com/77843345/105502995-aa29ae80-5c8b-11eb-91e0-5f11eb094814.png">
Screenshot from iPhone Xs Max: 
- <img width="300" alt="Screenshot 2021-01-22 at 8.31.35 AM" src="https://user-images.githubusercontent.com/77843345/105504806-d0504e00-5c8d-11eb-9cb0-979a881f00fb.png">
Telegram iOS Client v7.3.1: 
- <img width="300" alt="Telegram iOS Client Version" src="https://user-images.githubusercontent.com/77843345/105505707-e7dc0680-5c8e-11eb-9dbc-fb5209db0bd6.png">
iOS v14.3: 
- <img width = "300" alt="iOS version" src="https://user-images.githubusercontent.com/77843345/105505299-6a17fb00-5c8e-11eb-9115-3640f70b9fa4.png">

Cheers,
Phil

**Comment by ed-asriyan** [comment]
Hello @phil-bryant!

Thank you for detailed issue description.
Please try again, the problem should be resolved.
