### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RickyBush** [ed-asriyan/tgs-to-gif#35]
Why do I always get this on the iOS stickers they work some times then I get this error thing the other times Queued (2907) 🤔💚

**Comment by ed-asriyan** [comment]
Hello, @RickyBush!
There was a problem with converting sticker thumbnails in [@tgtowabot]https://t.me/tgtowabot. Now the issue is resolved (thanks for https://github.com/lovell/sharp/issues/2570#issuecomment-776228960), so the queue should be decreased soon.
