### ISSUE TITLE
Can't convert this one

### ISSUE THREAD

**Issue by hupo376787** [ed-asriyan/tgs-to-gif#38]
It should be
![663b0491ly1gozf5aqikzg20e80e84qq](https://user-images.githubusercontent.com/14960168/112740727-01ad0900-8fb2-11eb-83a9-444469fb9729.gif)

[AnimatedSticker.zip](https://github.com/ed-asriyan/tgs-to-gif/files/6216765/AnimatedSticker.zip)

**Comment by ed-asriyan** [comment]
Please, provide console output
