### ISSUE TITLE
It's not working since a day, everything goes into queue and nothing happens..

### ISSUE THREAD

**Issue by rgs09** [ed-asriyan/tgs-to-gif#41]
![image](https://user-images.githubusercontent.com/82146634/115337492-b35ce580-a1be-11eb-9d82-68518ac5e1db.png)
![image](https://user-images.githubusercontent.com/82146634/115337509-bbb52080-a1be-11eb-83e8-89286bfc6dd6.png)

**Comment by ed-asriyan** [comment]
Hello!
There were maintenance works. At the moment the problem is fixed.
