### ISSUE TITLE
64x64 resolution?

### ISSUE THREAD

**Issue by CommanderTvis** [ed-asriyan/tgs-to-gif#44]
I'm re-uploading some Telegram stickers to a service that has a 512 KiB size limit for each gif, and it would be nice to have a 64x64 resolution.

**Comment by ed-asriyan** [comment]
To convert Telegram sticker to GIF with custom resolution, use this tool as follows:
```console
$ node cli.js /home/ed/Downloads/super_pack/ --height 64 --width 64
```
