### ISSUE TITLE
"An error occurred. Please, try again later."

### ISSUE THREAD

**Issue by nwaspher** [ed-asriyan/tgs-to-gif#46]
All of your bots and your app are top notch and I'm thankful as hell for them as there's no real good alternative to them in my opinion, but, I don't know why, I simply can't convert this pack: 
- https://t.me/addstickers/Cat_MTHRK1

I even tried converting it manually, but no success

**Comment by ed-asriyan** [comment]
cached file_id was invalid. fixed now. please, try again
