### ISSUE TITLE
This use cache?, can I use cache for seperate sticker files?

### ISSUE THREAD

**Issue by sentinm** [ed-asriyan/tgs-to-gif#47]
> Sticker you sent seems not to be from a sticker pack (are you send me a .tgs file?).
> 
> I'll convert it, but the next time I ask you to send me a sticker from a sticker pack, because I use caches to not convert the same sticker twice, and I can cache only stickers from sticker packs. The sticker will be converted with low priority.

Do this uses cache for telegram sticker packs (.tgs), and can I get seperate caches for seperate stickers?

**Comment by ed-asriyan** [comment]
No. The bot caches sticker packs, not single stickers.

**Comment by sentinm** [comment]
Ok thanks, you mean the bot uses cache for sticker packes or library use cache for sticker packes?

**Comment by ed-asriyan** [comment]
> Ok thanks, you mean the bot uses cache for sticker packes or library use cache for sticker packes?

I mean the bot. tgs-to-gif does not caches the data.

**Comment by sentinm** [comment]
> No. The bot caches sticker packs, not single stickers.

    Owh ok, thanks
