### ISSUE TITLE
does not work when file name contains '('

### ISSUE THREAD

**Issue by kamaljeet** [ed-asriyan/tgs-to-gif#48]
filename:  AnimatedSticker (1).tgs

[kj@uno tgs-to-gif]$ node cli.js /home/kj/Downloads/Telegram\ Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker (1).tgs
bash: syntax error near unexpected token `('

[kj@uno tgs-to-gif]$ 
[kj@uno tgs-to-gif]$ 
[kj@uno tgs-to-gif]$ 
[kj@uno tgs-to-gif]$ 
[kj@uno tgs-to-gif]$ node cli.js /home/kj/Downloads/Telegram\ Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker\ \(1\).tgs
Converting /home/kj/Downloads/Telegram Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker (1).tgs...
✔ Loading browser
✔ Rendering 180 frames
⠋ Generating GIF with GifskiError: Command failed: /bin/sh -c gifski -o /home/kj/Downloads/Telegram\ Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker\ (1).tgs.gif --fps 50 --quality 80 --quiet /tmp/96defc45f1ea964839e07576ca6986c7/frame-*.png
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `gifski -o /home/kj/Downloads/Telegram\ Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker\ (1).tgs.gif --fps 50 --quality 80 --quiet /tmp/96defc45f1ea964839e07576ca6986c7/frame-*.png'

    at makeError (/home/kj/Code/node/tgs-to-gif/node_modules/execa/index.js:174:9)
    at /home/kj/Code/node/tgs-to-gif/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/kj/Code/node/tgs-to-gif/node_modules/puppeteer-lottie/index.js:422:5)
    at async convertFile (/home/kj/Code/node/tgs-to-gif/index.js:31:3)
    at async convertFiles (/home/kj/Code/node/tgs-to-gif/cli.js:12:7)
    at async main (/home/kj/Code/node/tgs-to-gif/cli.js:46:3) {
  code: 2,
  stdout: '',
  stderr: "/bin/sh: -c: line 1: syntax error near unexpected token `('\n" +
    "/bin/sh: -c: line 1: `gifski -o /home/kj/Downloads/Telegram\\ Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker\\ (1).tgs.gif --fps 50 --quality 80 --quiet /tmp/96defc45f1ea964839e07576ca6986c7/frame-*.png'\n",
  failed: true,
  signal: null,
  cmd: '/bin/sh -c gifski -o /home/kj/Downloads/Telegram\\ Desktop/DataExport_2021-11-10/chats/chat_4/stickers/AnimatedSticker\\ (1).tgs.gif --fps 50 --quality 80 --quiet /tmp/96defc45f1ea964839e07576ca6986c7/frame-*.png',
  timedOut: false,
  killed: false
}
⠸ Generating GIF with Gifski

**Comment by ed-asriyan** [comment]
fixed
