### ISSUE TITLE
why the gif looks like sawtooth

### ISSUE THREAD

**Issue by diybl** [ed-asriyan/tgs-to-gif#5]
[](url)
![QQ图片20200327231745](https://user-images.githubusercontent.com/578430/77771058-2ad64900-7081-11ea-9c59-6c9def586c92.png)

**Comment by ed-asriyan** [comment]
Because GIF -- is a **raster** animated image. To make an image less sawtooth increase its resolution by passing `--width` and/or `--height` arguments. See [README CLI Arguments](https://github.com/ed-asriyan/tgs-to-gif#cli-arguments).
