### ISSUE TITLE
Whether to consider writing a golang version

### ISSUE THREAD

**Issue by jw-star** [ed-asriyan/tgs-to-gif#50]

**Comment by ed-asriyan** [comment]
Hello! For what purpose?

**Comment by jw-star** [comment]
go found that the tgs to gif api does not have go, it seems difficult to achieve go

**Comment by ed-asriyan** [comment]
If you want you can make golang version by yourself in a fork or your own repo with optimizations. Sorry, but I am not ready to spend time for rewriting from typescript to golang

fyi, there is C++ version in master-cpp branch
