### ISSUE TITLE
all converted gifs has a blank frame

### ISSUE THREAD

**Issue by allnan** [ed-asriyan/tgs-to-gif#7]
![image](https://user-images.githubusercontent.com/17645490/77843411-ab0ac480-71cf-11ea-95ac-b51f472f8474.png)

First,thanks for your tool,do you have any idea how to get rid of this last frame.

**Comment by ed-asriyan** [comment]
It seems to be a puppeteer-lottie bug. I sent PR to fix it: https://github.com/transitive-bullshit/puppeteer-lottie/pull/23.

**Comment by ed-asriyan** [comment]
@allnan thank you! Please, pull master branch, run `npm install` and try again, issue should be resolved.

**Comment by allnan** [comment]
It's worked!
Thank you very much.
