### ISSUE TITLE
Windows documentation: how to convert all files in all subdirectories

### ISSUE THREAD

**Issue by Meteor0id** [ed-asriyan/tgs-to-gif#70]
Make sure you have installed node.js and unpacked gifski and C:\gifski-1.7.0\win is listed in your path in system-variables. If you have to add it to your path you have to reopen cmd for it to take effect.

Create a .bat file with the following code (change the paths to you needs)
`
REM chcp 65001 allows handling directories and files with unusual non-ascII chars
chcp 65001
for /f "usebackq delims=|" %%f in (`dir /b /s "C:\All stickerpacks\**.tgs"`) do node "C:\tgs-to-gif-master\cli.js" "%%f"
pause
`

if you use nvm to install node.js you may also have to install lottie

**Comment by ed-asriyan** [comment]
the tool has been rewritten by scratch

please use [docker version](https://github.com/ed-asriyan/tgs-to-gif#using-docker) which supports batch converting or [build from sources](https://github.com/ed-asriyan/tgs-to-gif#from-source) then use bash for example
```bash
find $PATH_TO_DIRECTORY_WITH_STICKERS -name '*.tgs' | while IFS=$'\n' read -r FILE; do 
  ./bin/tgs_to_gif.sh $FILE
done
```
