### ISSUE TITLE
How to convert TGS to APNG? 

### ISSUE THREAD

**Issue by AvanZ69** [ed-asriyan/tgs-to-gif#82]
Hi guys, I don't have much knowledge about coding. I was easily able to converts stickers to GIFs using the bot, but from the readme.txt where you explained a way how we can convert stickers to APNG, I couldn't understand the process. Can you explain it simply?

**Comment by ed-asriyan** [comment]
1. Install [Docker Desktop](https://www.docker.com)
2. Download all .tgs images you want to convert to one directory
3. Run the following command in terminal (replace `replace_with_path_to_directory_with_stickers` with path to directory with stickers):
    ```terminal
    docker run --rm -v replace_with_path_to_directory_with_stickers:/source edasriyan/tgs-to-apng
   ```
   More info here: https://github.com/ed-asriyan/tgs-to-gif#using-docker
